trigger:
  branches:
    include:
      - master
  paths:
    include:
      - projects/database/src/seeders
pool:
  vmImage: ubuntu-latest

variables:
  root: '$(System.DefaultWorkingDirectory)/projects/database/'
  source: '$(System.DefaultWorkingDirectory)/projects/database/src/management'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(root)
    Contents: 'package.json'
    TargetFolder: $(source)

- task: CopyFiles@2
  inputs:
    SourceFolder: $(source)
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Database-Migrations'
    publishLocation: 'Container'