# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
   include:
     - master
  paths:
      include:
        - projects/web-client
      exclude:
        - projects/docs

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'a312dcf7-69ea-4b41-ba8d-4d52e4e9eaa6'
  imageRepository: 'webclient'
  containerRegistry: 'hexhchess.azurecr.io'
  dockerfilePath: 'projects/web-client/Dockerfile'
  tag: '$(Build.BuildId)'
  root: '$(System.DefaultWorkingDirectory)/projects/web-client'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: >
      echo
      'registry=https://pkgs.dev.azure.com/michallukasiewicz/HexChess/_packaging/HexChess/npm/registry/' 
      >> .npmrc
    workingDirectory: $(root)
- task: npmAuthenticate@0
  inputs:
    workingFile: '$(root)/.npmrc'
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: $(root)
    tags: $(tag)