export const BLOB_CLIENT_OPTIONS = 'BLOB_CLIENT_OPTIONS';
export const BLOB_CONTAINER_NAME = 'BLOB_CONTAINER_NAME';
export const BLOB_STORAGE_ROOT_MODULE = 'BLOB_STORAGE_ROOT_MODULE';
export const BLOB_DEFAULT_CLIENT = 'BLOB_DEFAULT_CLIENT';
export const BLOB_MODULE_STORAGE = 'BLOB_MODULE_STORAGE';